flask_portfolio/app/__init__.py
from flask import Flask, session


def create_app():
    app = Flask(__name__)
    
    # Configuration settings can go here
    app.config['SECRET_KEY'] = 'your_secret_key'
    from .routes import main, morse_code, tic_tac_toe

    app.register_blueprint(main, url_prefix="/")
    app.register_blueprint(morse_code, url_prefix="/morse_code")
    app.register_blueprint(tic_tac_toe, url_prefix="/tictactoe")
    
    return app

flask_portfolio/app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, make_response
from morse_code import text_to_morse
from tictactoe import TicTacToe

# Define blueprints
main = Blueprint('main', __name__)
morse_code = Blueprint('morse_code', __name__)
tic_tac_toe = Blueprint('tic_tac_toe', __name__)

@main.route("/")
def home():
    return render_template('index.html')


@morse_code.route("/")
def home():
    text_to_translate='Hello Stranger!'
    return render_template(
        'morse_code.html',
        text_to_translate=text_to_translate,
        translation=text_to_morse(text_to_translate)
        )


@morse_code.route("/translate_to_morse", methods=['POST'])
def translate_to_morse():
    if request.method == "POST":
        text_to_translate = request.form['text_to_translate']
        translation = text_to_morse(text_to_translate)
        return render_template(
            'morse_code.html', 
            text_to_translate=text_to_translate, 
            translation=translation
            )
    return redirect(url_for('morse_code.home'))


@tic_tac_toe.route("/")
def home():
    return render_template(
        'tictactoe.html', 
        game_started=False
    )


@tic_tac_toe.route("/start_game", methods=['POST'])
def start_game():
    player = request.json['player'].lower()
    game = TicTacToe()
    session['player_x'] = game.player_x
    session['player_o'] = game.player_o
    return jsonify(player=player)


def change_player(player):
    return 'x' if player == 'o' else 'o'


def update_game_session(game: TicTacToe):
    session['player_x'] = game.player_x
    session['player_o'] = game.player_o


def to_move(player):
    if player == 'x':
        return not (len(session['player_x']) < 3)
    return not (len(session['player_o']) < 3)


def get_game_from_session() -> TicTacToe:
    return TicTacToe(session['player_x'], session['player_o'])


@tic_tac_toe.route("/place", methods=['POST'])
def place():
    player = request.json['player']
    if to_move(player):
        return jsonify(error="Please choose a brick to move."), 400
    index = int(request.json['index'])
    game = get_game_from_session()
    try:
        game.place(player, index)
        game_over = game.check_win(player)
        player = change_player(player)
        update_game_session(game)
        return jsonify(
            player=player,
            available_spots=list(game.get_avaliable_slots()),
            game_over=game_over
        )
    except:
        return jsonify(error="Please place at an unoccupied slot."), 400
    
@tic_tac_toe.route("/move", methods=["POST"])
def move():
    player = request.json['player']
    index = int(request.json['index'])
    if not to_move(player):
        return jsonify(error="You need to place a brick."), 400
    try:
        game = get_game_from_session()
        game.move(player, index)
        update_game_session(game)
        return jsonify(
            player=player,
            available_spots=list(game.get_avaliable_slots()),
        )
    except:
        return jsonify(error="Please pick an available brick to move"), 400

flask_portfolio/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
</head>
<body>
    <h1>Welcome to My Portfolio</h1>
    <p>This is a showcase of my projects.</p>
    <ul>
        <li><a href={{ url_for('morse_code.home') }}>Morse code page</a></li>
        <li><a href={{ url_for('tic_tac_toe.home')}}>TicTacToe</a></li>
    </ul> 
</body>
</html>

flask_portfolio/app/templates/morse_code.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
</head>
<body>
    <h1>Welcome to the morse code page</h1>
    <form action={{ url_for('morse_code.translate_to_morse') }} method="post">
        <label for="text_to_translate">Enter text to translate:</label>
        <input type="text" id="text_to_translate" name="text_to_translate" required>
        <input type="submit" value="Translate">
    </form>
    <p>Translation: '{{ text_to_translate }}' = '{{ translation  }}'</p>
    <a href={{ url_for('main.home') }}>Home</a>
</body>
</html>

flask_portfolio/app/templates/tictactoe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/tictactoe.css') }}">
    <title>Portfolio</title>
</head>
<body start-player-url="{{ url_for('tic_tac_toe.start_game') }}" place-url="{{ url_for('tic_tac_toe.place') }}" move-url="{{ url_for('tic_tac_toe.move') }}">
    <h1>Welcome to Tic tac toe</h1>
    <h2>TicTacToe Game</h2>
    <div id="choose-start-player">
        <span>Select starting player</span>
        <button class="player-choice">X</button>
        <button class="player-choice">O</button>
    </div>
    <p id="instructions"></p>
    <div id="error-message" style="display: none; color: red;"></div>
    <div id="win-message" style="display: none; color: green;"></div>
    <div class="board">
        {% for i in range(9) %}
            <div id="cell{{ i + 1 }}" class="cell" slot-occupied="false"></div>
        {% endfor %}
    </div>
    <a href={{ url_for('tic_tac_toe.home') }} id="reset-game"><button>Reset Game</button></a>
    <br>
    <a href={{ url_for('main.home') }}>Home</a>

    <script src="{{ url_for('static', filename='js/tictactoe.js') }}"></script>
</body>
</html>